bonus: Stealthed
ability_score:
  primary: dexterity
  secondary:
    - strength
    - charisma
paragon: Master Infiltator
powers:
  cloud_of_steel:
    name: Cloud Of Steel
    type: at_will
    range: "60' range"
    desc: "Toss a barrage of blades at your target, dealing medium damage. The longer you flurry a single target, the more damage Cloud of Steel will inflict."
    rank_2: "Damage: +10%"
    rank_3: "Damage: +10%" 
    level: 0
  sly_flourish:
    name: Sly Flourish
    type: at_will
    range: "2' cylinder"
    desc: "A distracting flourish of your blades deals damage to your target."
    rank_2: "Damage: +10%" 
    rank_3: "Damage: +10%" 
    level: 0
  dazing_strike:
    name: Dazing Strike
    type: encounter
    range: "3' cylinder"
    cooldown: 10
    desc: "Snap into the air, catching your opponent with a crushing blow to their head. The impact causes your opponent to be Dazed for several seconds." 
    bonus: "During Stealth, activation time reduced by 50%."
    rank_2: "Damage: +10%" 
    rank_3: "Damage: +10%" 
    level: 0
  bloodbath:
    name: Bloodbath
    type: daily
    range: "30' burst"
    desc: "Flash around the battlefield, jumping from target to target. As you pass through an enemy, they are Slowed and are open to Combat Advantage."
    rank_2: "Damage: +10%" 
    rank_3: "Damage: +10%" 
    level: 0
  sneak_attack:
    name: Sneak Attack
    type: skill
    desc: "Increase your Run Speed by 10% while Stealthed."
    rank_2: "Damage: +10%" 
    rank_3: "Damage: +10%" 
    level: 0
  deft_strike:
    name: Deft Strike
    type: encounter
    range: "60' range"
    cooldown: 14
    desc: "Dash behind your enemy and deliver a painful stab, Slowing your enemy for a short duration."
    bonus: "During Stealth, range increased to 80' and allow you to teleport to friendly targets."
    rank_2: "Damage: +10%" 
    rank_3: "Damage: +10%" 
    level: 5
  lashing_blade:
    name: Lashing Blade
    type: encounter
    range: "14' range, 3' cylinder"
    cooldown: 20
    desc: "Focus your strength into one furious attack, inflicting massive damage on your enemy."  
    bonus: "During Stealth, deals an additional 50% damage." 
    rank_2: "Damage: +10%" 
    rank_3: "Damage: +10%" 
    level: 5
  lurkers_assault:
    name: Lurkers Assault
    type: daily
    desc: "Lurk through the shadows, adding +20% damage to your attacks and your Stealth meter regenerates very quickly in this state, allowing you to remain Stealthed for much longer."
    rank_2: "Damage: +20%" 
    rank_3: "Damage: +20%"  
    level: 10
  whirlwind_of_blades:
    name: Whirlwind Of Blades
    type: daily
    range: "30' burst"
    desc: "Whip your daggers out around you, dealing minor damage but gaining Power for each enemy you hit."
    rank_2: "Damage: +10%"  
    rank_3: "Damage: +10%"  
    level: 10
  bait_and_switch:
    name: Bait And Switch
    type: encounter
    range: "15' blast"
    cooldown: 25
    desc: "Jump backwards, dropping a decoy in your place. Any enemies that are near the decoy will attack it instead of you. Gain Action Points when the decoy is hit by an enemy."
    bonus: "Refills your stealth bar and does not remove you from Stealth."
    rank_2: "Decoy Hitpoints: +10%, Action Points from Decoy: +1%"
    rank_3: "Decoy Hitpoints: +10%, Action Points from Decoy: +1%"
    level: 15
  first_strike:
    name: First Strike
    type: skill
    desc: "Your first attack in combat deals 5% additional damage"
    rank_2: "Damage: +5%"  
    rank_3: "Damage: +5%"  
    level: 15
  tenacious_concealment:
    name: Tenacious Concealment
    type: skill
    desc: "Reduces Stealth loss from incoming damage by 30%"
    rank_2: "Stealth Loss: -30%"
    rank_3: "Stealth Loss: -30%"
    level: 15
  duelists_flurry:
    name: Duelists Flurry
    type: at_will
    range: "2' cylinder"
    desc: "Strike with two slashes followed by a flurry of attacks. Attacks from the flurry each have a chance to add a Bleed effect which can be stacked up to 10 times."
    rank_2: "Damage: +10%"  
    rank_3: "Damage: +10%"  
    level: 20
  blitz:
    name: Blitz
    type: "encounter"
    range: "40' range, 90' cone"
    cooldown: 12
    desc: "Throw a fan of blades out directly in front of you."
    bonus: "During Stealth, slows all targets hit for 3 seconds."
    rank_2: "Damage: +10%"  
    rank_3: "Damage: +10%"  
    level: 20
  tactics:
    name: Tactics
    type: skill
    desc: "Increases your Action Point Gain by 5%"
    rank_2: "Action Point Gain: +5%"
    rank_3: "Action Point Gain: +5%"
    level: 20
  impossible_to_catch:
    name: Impossible To Catch
    paragon: "Inflitrator"
    type: encounter
    cooldown: 18
    desc: "You break free from most control effects, and for several seconds you Deflect all incoming attacks and are immune to further control effects."
    bonus: "You become completely untouchable to your enemies, dodging their attacks and receiving no damage."
    rank_2: "Buff Duration: +1s"
    rank_3: "Buff Duration: +1s"
    level: 30
  infiltrators_action:
    name: Infiltrators Action
    type: skill
    paragon: "Inflitrator"
    desc: "Every time you do a daily, gain Combat Advantage for 5 secs."
    rank_2: "Duration: +5"
    rank_3: "Duration: +5"
    level: 30
  path_of_the_blade:
    name: Path Of The Blade
    type: encounter
    cooldown: 25
    desc: "Summon an upheaval of powerful blades around you, dealing damage to nearby enemies for the next several seconds."
    bonus: "Pulses twice as fast for half of the duration."
    rank_2: "Damage: +10%"
    rank_3: "Damage: +10%"
    level: 30
  impact_shot:
    name: Impact Shot
    type: encounter
    range: "40' range"
    cooldown: 0
    desc: "Attack your opponent from a medium range, Pushing them slightly. This skill has 3 encounter charges."
    bonus: "Briefly Stuns the target, and cost no charges."
    rank_2: "Damage: +10%"
    rank_3: "Damage: +10%"
    level: 35
  gloaming_cut:
    name: Gloaming Cut
    type: at_will
    paragon: "Inflitrator"
    range: "20' range, 2' cylinder"
    desc: "Dash forward with a shadowy cross slash that grants 25% of your Stealth bar if you kill a target with it."
    rank_2: "Damage: +10%"
    rank_3: "Damage: +10%"
    level: 35
  skillful_infiltrator:
    name: Skillful Infiltrator
    type: skill
    paragon: "Inflitrator"
    desc: "Increase your base run speed by 5%, and your Deflect Chance and Crit Chane by 1%."
    rank_2: "Run Speed: +5%, Crit Chance: +1%, Dodge Chance: +1%"
    rank_3: "Run Speed: +5%, Crit Chance: +1%, Dodge Chance: +1%"
    level: 40
  courage_breaker:
    name: Courage Breaker
    type: daily
    range: "45' range"
    desc: "Shatter your enemy's courage, slowing their movement speed and lowering their attack damage by 30%. This effect goes through control immunities."
    rank_2: "Damage Reduction: +30%"
    rank_3: "Damage Reduction: +30%"
    level: 40
  wicked_reminder:
    name: Wicked Reminder
    type: encounter
    range: "3' cylinder"
    cooldown: 4
    desc: "Pierce your enemy's armor, cracking it for a period of time, lowering your target's Damage Resistance. This effect can stack up for 5 times."
    bonus: "Applies 3 stacks."
    rank_2: "Damage: +10%"
    rank_3: "Damage: +10%"
    level: 45
  shadow_strike:
    name: Shadow Strike
    type: encounter
    range: "40' range"
    cooldown: 16
    desc: "Strike your target from a medium range and fill your Stealth bar."
    bonus: "Dazes target for a short duration, and does not remove Stealth."
    rank_2: "Damage: +10%"
    rank_3: "Damage: +10%"
    level: 45
  invisible_infiltrator:
    name: Invisible Infiltrator
    type: skill
    paragon: "Inflitrator"
    desc: "After using a daily, refills your Stealth meter and grants a 5% damage bonus for 5 seconds."
    level: 50
  shocking_execution:
    name: Shocking Execution
    type: daily
    paragon: "Inflitrator"
    range: "30' range"
    desc: "Leap up and strike with a vicious attack that ignores your targets' defense and deals additional damage based an how much health they are missing."
    level: 50
  smoke_bomb:
    name: Smoke Bomb
    type: encounter
    cooldown: 18
    desc: "Drop a smoke bomb in front of you, Dazing opponents while inside of it."
    bonus: "Now adds a Slow effect."
    rank_2: "Duration: +1"
    rank_3: "Duration: +1"
    level: 50

feats:
  heroic: 
    - 
      key: action_advantage
      name: Action Advantage
      points: 5 
      desc: "2/4/6/8/10% additional Action Point for dealing Combat Advantage damage."
      type: tactical
    -
      key: weapon_mastery
      name: Weapon Mastery
      points: 3 
      desc: "1/2/3% greater chance to land a critical hit."
      type: assault
    -
      key: toughness
      name: Toughness
      points: 3 
      desc: "Increase your Maximum Hit Points by 3/6/9%."
      type: enduring2
    -
      key: swift_footwork
      name: Swift Footwork
      points: 5 
      desc: "Your Stamina regenerates 2/4/6/8/10% faster."
      type: surefooted
    -
      key: battlewise
      name: Battlewise
      points: 3 
      desc: "You create 2/4/6% less threat."
      type: strategy
    -
      key: cunning_ambusher
      name: Cunning Ambusher
      points: 3 
      desc: "You deal 2/4/6% more damage for 6 seconds after leaving Stealth"
      type: intellect
    -
      key: endless_assault
      name: Endless Assault
      points: 3 
      desc: "Your encounters deal 2/4/6% more damage."
      type:  damage
    -
      key: twilight_adept
      name: Twilight Adept
      points: 5 
      desc: "Restores 2/4/6/8/10% of your Stealth Meter when you Dodge Roll."
      type: intellect
    -
      key: lucky_skirmisher
      name: Lucky Skirmisher
      points: 3 
      desc: "Increase your chance to Deflect by 1/2/3%."
      type: chance
    -
      key: scoundrel_training
      name: Scoundrel Training
      points: 3 
      desc: "Your At-Wills deal 3/6/9% more damage to foes not targeting you."
      type: agility
    -
      key: disciple_of_strength
      name: Disciple Of Strength
      points: 3 
      desc: "Increase the amount of bonus damage Strength gives you by 5/10/15%."
      type: power
    -
      key: improved_cunning_sneak
      name: Improved Cunning Sneak
      points: 5 
      desc: "Your Stealth lasts 4/8/12/16/20% longer."
      type: cunning2
  saboteur:
    -
      key: speed_swindle
      name: Speed Swindle
      points: 5 
      desc: "When you crit a foe it loses 2/4/6/8/10% Run Speed, you gain 2/4/6/8/10%."
      type: agility
    -
      key: cunning_stalker
      name: Cunning Stalker
      points: 5 
      desc: "While Stealthed, you build 4/8/12/16/20% more Action Points."
      type: agility
    -
      key: nimble_dodge
      name: Nimble Dodge
      points: 5 
      desc: "Your dodge costs 2/4/6/8/10% less Stamina. This reduction is doubled while Stealthed."
      type: surefooted
    -
      key: sneaky_stabber
      name: Sneaky Stabber
      points: 5 
      desc: "Your Gloaming Cut now grants 2/4/6/8/10% of your Stealth meter."
      type: assault
    -
      key: baited_action
      name: Baited Action
      points: 5 
      desc: "Your Bait and Switch Dummy has 2/4/6/8/10% more health and reflects 1/2/3/4/5% of damage delt to it."
      type: presence2
    -
      key: expert_sneak
      name: Expert Sneak
      points: 5 
      desc: "While Stealthed, you gain 2/4/6/8/10% Run speed and your At Will Powers reduce your target’s damage by 1/2/3/4/5%"
      type: presence2
    -
      key: sneak_of_shadows
      name: Sneak Of Shadows
      points: 5 
      desc: "Deal 2/4/6/8/10% more damage while Stealthed."
      type: cunning
    -
      key: unerring_ambush
      name: Unerring Ambush
      points: 5 
      desc: "Strikes with Deft Strike, Dazing Strike and Blitz deal 4/8/12/16/20% more damage from Stealth."
      type: agility
    -
      key: ruthless_efficiency
      name: Ruthless Efficiency
      points: 1 
      desc: "When you land a killing blow, your Armor Pen is increased by 30% for 6 seconds."
      type: courage
  scoundrel:
    -
      key: berserk_vitality
      name: Berserk Vitality
      points: 5 
      desc: "Gain .5/1/1.5/2/2.5% of your Max Hit Points as Temporary Hit Points when you deal Combat Advantage damage to a foe. This can only occur once every 20 seconds."
      type: enduring2
    -
      key: underhanded_tactics
      name: Underhanded Tactics
      points: 5 
      desc: "Increase the effectiveness of Combat Advantage for you by 4/8/12/16/20%"
      type: cunning2
    -
      key: press_the_advantage
      name: Press The Advantage
      points: 5 
      desc: "Your Impossible to Catch now also improves your Power by 2/4/6/8/10%"
      type: damage2
    -
      key: nimble_blade
      name: Nimble Blade
      points: 5 
      desc: "35% chance to deal an additional 4/8/12/16/20% damage on a non critical strike."
      type: assault
    -
      key: mocking_knave
      name: Mocking Knave
      points: 5 
      desc: "Sly Flourish and Cloud of Steel deal 2/4/6/8/10% more damage. Additionally, Cloud of Steel’s damage bonus per stack is increased by .5/1/1.5/2/2.5%."
      type: cunning
    -
      key: catspaw_style
      name: Catspaw Style
      points: 5 
      desc: "Your Blitz and Dazing Strike reduce the target’s defenses by 2/4/6/8/10%. This effect can not stack."
      type: cunning
    -
      key: action_rush
      name: Action Rush
      points: 5 
      desc: "Your Encounter Powers have a 15% chance to grant 3/6/9/12/15% of your Action Point"
      type: presence2
    -
      key: brutal_wound
      name: Brutal Wound
      points: 5 
      desc: "Courage Breaker and Whirlwind of Blades also deal 50/100/150/200/250% of your weapon damage over 5 seconds."
      type: poison
    -
      key: whirlwind_sneak_attack
      name: Whirlwind Sneak Attack
      points: 1 
      desc: "For 10 seconds after Stealth ends, the first time you hit with an encounter power it will deal 15% additional damage."
      type: damage
  executioner:
    -
      key: dazzling_blades
      name: Dazzling Blades
      points: 5 
      desc: "Your At-Will powers have a 3/6/9/12/15% chance to reduce the cooldown on recharging Encounter powers by 1 second."
      type: poison
    -
      key: thrill_of_the_kill
      name: Thrill Of The Kill
      points: 5 
      desc: "When you land a killing blow, gain .2/.4/.6/.8/1% of your Action Points."
      type: cunning
    -
      key: crueltys_reward
      name: Crueltys Reward
      points: 5 
      desc: "When you critically strike a foe you generate 2/4/6/8/10% less threat for 6 seconds."
      type: presence2
    -
      key: devastating_shroud
      name: Devastating Shroud
      points: 5 
      desc: "Increase your critical strike chance and severity by 2/4/6/8/10% for 6 seconds after using Shocking Execution."
      type: damage
    -
      key: brutal_backstab
      name: Brutal Backstab
      points: 5 
      desc: "While Stealthed you critical with 5/10/15/20/25% more severity."
      type: power
    -
      key: critical_teamwork
      name: Critical Teamwork
      points: 5 
      desc: "You and your nearby allies gain a 1/2/3/4/5% chance to crit."
      type: strategy
    -
      key: deadly_momentum
      name: Deadly Momentum
      points: 5 
      desc: "Duelist’s Flurry has a 5/10/15/20/25% chance to apply ‘Deadly Momentum’ Deadly Momentum; Increases your critical severity by 5% per stack."
      type: heritage2
    -
      key: sharpened_steel
      name: Sharpened Steel
      points: 5 
      desc: "Blitz and Wicked Reminder have 2/4/6/8/10% more chance to crit."
      type: assault
    -
      key: overrun_critical
      name: Overrun Critical
      points: 1 
      desc: "When you land a critical hit, one of your next attacks strikes with 30% of your crit severity."
      type: presence2
